### ISSUE TITLE
How can i translate this to my language?

### ISSUE THREAD

**Issue by nutsupra** [sk5s/countdateapp#28]
I want to translate the edit button, settings button, and toggle button (countdown, countup,)

**Other languages:**

![](https://cdn.discordapp.com/attachments/1039194766031736893/1134314339235541092/IMG_20230728_093617.jpg)

**In my thai language:**

![](https://cdn.discordapp.com/attachments/1039194766031736893/1134314339478802452/IMG_20230728_093631.jpg)

Keyword for me: When I hold down button, it will show "http://localhost/settings" or "http://localhost/edit"

![](https://cdn.discordapp.com/attachments/1039194766031736893/1134316784628023386/IMG_20230728_094823.jpg)

Wrong Thai Grammar and Auto translate... Because i cannot edit it. In thai language not have between words (But i can edit it in th.json)

![](https://cdn.discordapp.com/attachments/1039194766031736893/1134316785085198377/IMG_20230728_094851.jpg)

**Comment by nutsupra** [comment]
Sorry for my communication problem. But I think you can understand.

**Comment by sk5s** [comment]
1. Please see the file I edited, it includes translate strings: https://github.com/sk5s/countdateapp/blob/main/src/i18n/data/th.json  line 21-22.
2. The dragged text is the same in all language because the button is a link. This is not a translate issue.
3. Wrong Thai Grammar: This problem is because some grammar and blank are hard coded in the source code. To solve this issue, all language string files and the code need to rewrite.

Because there are many files need to edit, this issue may need more time to solve. I want to invite you to translate it again after I rewrite the code.

**Comment by sk5s** [comment]
Hi @nutsupra , this is the brand new translate file https://github.com/sk5s/countdateapp/blob/main/src/i18n/data/th.json . Since I have rewrite the code, I think it can match the Thai grammar now.
