### ISSUE TITLE
feat: support hours and minutes

### ISSUE THREAD

**Issue by ni720** [sk5s/countdateapp#36]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be useful if hours and minutes are also supported, that way deadlines for example on the end of the workday could be better presented.

### Describe the Use Case

User has a deadline on a specific day, on a specific hour or hour and minute.

### Describe Preferred Solution

It would be perfect if the widget also supported hours and minutes.

**Comment by sk5s** [comment]
Hi, thanks for your proposal!
However, we decide not to implement this feature. We want to keep the app simple to use and functional simultaneously. Because the Countdate app was initially designed to count how many days are left, too much detail may make the app more complex than before.
We are willing to receive proposals and issues. If you find where the app can improve, feel free to open an issue!
